version: "3.2"
services:
  develop:
    container_name: node_base_project_hexagonal
    build:
      context: .
      target: development
      dockerfile: "Dockerfile"
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/html/
    restart: always
    working_dir: /var/www/html
    command: sh -c "npm install && npm run start:dev"
